name: container-build

on:
  workflow_dispatch:
    inputs:
      container_registry_push:
        description: "Push the image to Container Registry"
        type: boolean
        required: false
        default: false
      container_image_skip_vulnerability_checks:
        description: "Skip image (vulnerability) scanner"
        type: boolean
        required: false
        default: false
      container_image_expires_after:
        description: "Expires after (days) [or 'Never']"
        type: string
        required: false
        default: "730"
  push:
    tags:
      # For code tagging use 'v' prefix, but 'v' prefix should not be part of container tag
      - "v[0-9]+.[0-9]+.[0-9]+*"
  schedule:
    - cron: "0 0 * 1 1"

jobs:
  container-build-pipeline:
    name: "💡 ${{ matrix.container_image_dockerfile_location }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          # Contains several vulnerabilities
          - container_image_dockerfile_location: Dockerfile
            # This is the "default Dockerfile", which will create tags without any suffix (like 'latest')
            container_image_tag_suffix: ""
    uses: ruzickap/container-build/.github/workflows/container-build-reusable-workflow.yml@main
    with:
      container_image_dockerfile_location: ${{ matrix.container_image_dockerfile_location }}
      container_image_tag_suffix: ${{ matrix.container_image_tag_suffix }}
      # The following variables can not be easily taken to `env` variables, because it is not supported :-(
      container_image_destination: quay.io/petr_ruzicka/raw-photo-tools
      container_image_product_id: 12345
      container_image_vendor: MyCompany
      container_image_authors: petr.ruzicka@gmail.com
      container_image_repository_url: https://quay.io/repository/petr_ruzicka/raw-photo-tools?tab=tags
      container_image_expires_after: ${{ inputs.container_image_expires_after || '730' }} # days
      # https://github.com/actions/runner/issues/1483
      container_registry_push: ${{ inputs.container_registry_push == true && true || false }}
      container_image_skip_vulnerability_checks: ${{ inputs.container_image_skip_vulnerability_checks == true && true || false }}
    secrets:
      container_registry_user: ${{ secrets.CONTAINER_REGISTRY_USER }}
      container_registry_password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

  create-release:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euxo pipefail
          gh release create ${{ github.ref_name }} --generate-notes
